### ISSUE TITLE
Akka.HealthCheck.Persistence unit tests

### ISSUE THREAD

**Issue by Aaronontheweb** [petabridge/akkadotnet-healthcheck#13]
Need to validate the following via unit tests:

1.  [x] Should be able to load the `AkkaPersistenceLivenessProbeProvider` from HOCON configuration when starting up an `ActorSystem` with it configured
2. [x] The underlying `AkkaPersistenceLivenessProbe` should be able to correctly handle subscriptions in any state.
3. [x] The `AkkaPersistenceLivenessProbe` should correctly report that Akka.Persistence is available when it is
4. [x] The `AkkaPersistenceLivenessProbe` should correctly report that Akka.Persistence is NOT available when it isn't able to load at startup.
5. [x] The `AkkaPersistenceLivenessProbe` should correctly report that Akka.Persistence has become unavailable AFTER initially being available (simulate a future change in dis-connectivity.)
6. [x] Steps 4,5,6 should test both the Akka.Persistence Journal AND the SnapshotStore.

We will likely need to create some custom Akka.Persistence journal and SnapshotStore implementations in order to succeed in testing these - please take a look at some of the tests we have in the 

https://github.com/akkadotnet/akka.net/blob/e15b935b59e739220f28cb197bb191211e912bd4/src/core/Akka.Persistence.Tests/PersistentActorFailureSpec.cs#L49-L114

and 

https://github.com/akkadotnet/akka.net/blob/e15b935b59e739220f28cb197bb191211e912bd4/src/core/Akka.Persistence.Tests/SnapshotFailureRobustnessSpec.cs#L156-L168

**Comment by izavala** [comment]
Completed first task with pull request https://github.com/petabridge/akkadotnet-healthcheck/pull/14

**Comment by izavala** [comment]
AkkaPersistenceLivenessProveProvider should correctly handle subscription requests. 

https://github.com/petabridge/akkadotnet-healthcheck/pull/15

**Comment by izavala** [comment]
Create two separate test that change the configuration. Once for the journal and once for the snapshot store. This should cause Akka. Persistance to not load correctly, however AkkaPersistenceLIvenessProbe should be able to load and report it is not available.

**Comment by izavala** [comment]
Added test to check that livness is correctly reported when the akka.persistence journal or snapshot store is not setup correctly. https://github.com/petabridge/akkadotnet-healthcheck/pull/18
