### ISSUE TITLE
need to validate the nuget publication before 1.0 ships

### ISSUE THREAD

**Issue by Aaronontheweb** [petabridge/akkadotnet-healthcheck#155]
LGTM - need to validate the nuget publication locally (or check what the build server produced.) Don't want to publish any sample projects and need to make sure that the correct `README.md` files are included.

_Originally posted by @Aaronontheweb in https://github.com/petabridge/akkadotnet-healthcheck/pull/148#pullrequestreview-1227766460_

**Comment by Aaronontheweb** [comment]
@Arkatufus guess we'll do this via 1.0.0-beta1 and doing some integration testing into other projects / packages

**Comment by CumpsD** [comment]
I managed to implement 1.0.0-beta1 in my project fyi

For the Akka project I added:
```
  nuget Akka.HealthCheck 1.0.0-beta1
  nuget Akka.HealthCheck.Persistence 1.0.0-beta1
  nuget Akka.HealthCheck.Hosting.Web 1.0.0-beta1
```

Called
```csharp
AkkaHealthCheck.For(actorSystem);
```

And used hocon:
```
  healthcheck {
    log-config-on-start = on
    log-info = on

    liveness {
      transport = custom

      providers {
        default = "Akka.HealthCheck.Liveness.DefaultLivenessProvider, Akka.HealthCheck"
        persistence = "Akka.HealthCheck.Persistence.AkkaPersistenceLivenessProbeProvider, Akka.HealthCheck.Persistence"
      }
    }

    readiness {
      transport = custom

      providers {
        default = "Akka.HealthCheck.Readiness.DefaultReadinessProvider, Akka.HealthCheck"
      }
    }
  }
```

For ASP.NET integration I added:

```csharp
    using Akka.HealthCheck.Hosting.Web;

    .WithAkkaLivenessProbe()
    .WithAkkaReadinessProbe()
    .WithAkkaPersistenceLivenessProbe()

    endpoints
        .MapAkkaHealthCheckRoutes(
            HealthChecksWriter.HealthCheckEndpoint,
            (_, options) =>
            {
                options.AllowCachingResponses = false;
                options.ResponseWriter = HealthChecksWriter.WriteHealthCheckResponse;
            });
```

And everything worked for my use case :)

**Comment by Arkatufus** [comment]
@CumpsD You shouldn't need to set the HOCON settings when you use `Akka.HealthCheck.Hosting.Web`, and using the web package should pull the other packages as dependency

**Comment by CumpsD** [comment]
I like to be explicit with the packages :)

As for the HOCON, it's [`WithWebHealthCheck`](https://github.com/petabridge/akkadotnet-healthcheck/blob/dev/src/Akka.HealthCheck.Hosting.Web/AkkaWebHostingExtensions.cs#L222) which adds it no? And since I'm not using Akka.Hosting I don't have an AkkaBuilder which does that, no? I haven't converted to .Hosting yet

**Comment by Arkatufus** [comment]
Got it :)

**Comment by Aaronontheweb** [comment]
Related: https://github.com/akkadotnet/Akka.Hosting/issues/188
