### ISSUE TITLE
Akka.Persistence health checks create blobs but don't clean itself up

### ISSUE THREAD

**Issue by wesselkranenborg** [petabridge/akkadotnet-healthcheck#193]
During analysing our storage account blob snapshot folder I saw that I had a lot of Akka.Healthchecks snapshots. In the standup yesterday it was mentioned that the suicideProbe should cleanup the journal/snapshot store after it's tests. This is definetely not the case:

<img width="448" alt="image" src="https://user-images.githubusercontent.com/4964604/217731826-dcd773ef-7e1b-4050-bb18-642a4e1e6384.png">

At this moment this cluster only has 3 nodes, so old recycled nodes (pods) are still having snapshots/journal records lingering around.

It would be nice to remove the snapshot/journal records used for the healthprobe after the probe is finished. Off course you have the scenario that a pod could crash during the healthprobe, then you still get undeleted journal/snapshots but the chance of that happening is really low and I can live with that.

**Comment by Aaronontheweb** [comment]
cc @Arkatufus

**Comment by Arkatufus** [comment]
This is a side effect of this PR: https://github.com/petabridge/akkadotnet-healthcheck/pull/154

Old implementation would re-use the same persistence ID over and over again, minimalizing the database footprint but is not compatible when deployed inside a cluster. The new implementation makes persistence work inside a cluster/sharding, but it would not be able to clean up after itself

**Comment by wesselkranenborg** [comment]
Is it not possible to delete all journals and snapshots after execution? From the actor itself?

**Comment by Aaronontheweb** [comment]
@wesselkranenborg yes, it absolutely should be - the actor should delete its old records @Arkatufus

**Comment by Aaronontheweb** [comment]
this is definitely not an impossible engineering challenge to solve

**Comment by Aaronontheweb** [comment]
@Arkatufus isn't this fixed now?

**Comment by Aaronontheweb** [comment]
Yes, this was addressed in the 1.5.0.1 release.
