### ISSUE TITLE
Add debug option to log startup configuration at launch

### ISSUE THREAD

**Issue by Aaronontheweb** [petabridge/akkadotnet-healthcheck#34]
Should do a dump of all of the built-in HealthCheck settings at launch, so users can troubleshoot when first configuring the probes and transports.

**Comment by izavala** [comment]
Currently running into an issue implementing this logger, if the user inputs a HOCON file with the configuration, we do not have an ActorSystem to reference for the logger 

https://github.com/petabridge/akkadotnet-healthcheck/blob/dad6fe13d2a2ecb7a9701ba5072aca9a45640b35/src/Akka.HealthCheck/Configuration/HealthCheckSettings.cs#L28-L45

**Comment by izavala** [comment]
https://github.com/petabridge/akkadotnet-healthcheck/pull/37

**Comment by Aaronontheweb** [comment]
closed by #37
