### ISSUE TITLE
Add startup message indicating that liveness / readiness probes have been configured successfully

### ISSUE THREAD

**Issue by Aaronontheweb** [petabridge/akkadotnet-healthcheck#35]
Should log this automatically without any configuration settings - just to let the end-user know in the startup logs that the system is running with one or both of these tools enabled.

**Comment by izavala** [comment]
@Aaronontheweb Would the pull request https://github.com/petabridge/akkadotnet-healthcheck/issues/34 cover this as well? 

After dumping the configuration information it will let the user know if it the settings are configured correctly. It will not be specific as to whether the Liveness or Readiness probe is configured correctly.
